baseURL = "https://www.maugzoide.com/"
languageCode = "en-us"
title = "Mauricio Antunes"

theme = "hyde-hyde"

[params]
    author = "Maurício Antunes"
    title = "hello people"
    description = "people, technology, culture"
    authorimage = "/img/profile.png"
    highlightjs = true
    highlightjsstyle = "github"

[params.social]
    github = "mauricioabreu"
    twitter = "maugzoide"
    linkedin = "mauricio-abreu-antunes-3ba52013"
